### PR TITLE
fix for ESP32 Nimble: prvBTSetAdvData assumes exactly 1 UUID to be ad…

### LINKED ISSUE #1569: ESP32 Nimble: prvBTSetAdvData assumes exactly 1 UUID to be advertised
**Describe the bug**
In `iot_ble_hal_gap.c`, function `prvBTSetAdvData()` never uses the `xNbServices` parameter and assumes there is exactly 1 UUID to be advertised if `pxServiceUuid` is not NULL.
At the same time, `_setAdvData` always gives a value to `pxServiceUuid` and sets `xNbServices` as 0 if there are no UUIDs to advertise.
This means that trying to advertise 0 UUIDs (e.g. to save advertisement space) does not work. Trying to advertise 2 UUIDs would also not work.

**System information**
- Which hardware board or part numbers? ESP32
- IDE used. Does not matter.
- Operating System. Does not matter.
- Version of Amazon FreeRTOS. master
- Project: Custom Application

**Expected behavior**
The xNBServices should be used to advertise the requested number of UUIDs.

**To reproduce**

Just use a custom advertising callback like the following:

**Code to reproduce the bug**
```
void IotBle_SetCustomAdvCb(IotBleAdvertisementParams_t *pAdvParams,
                           IotBleAdvertisementParams_t *pScanParams)
{
  pAdvParams->setScanRsp          = false;
  pAdvParams->includeTxPower      = false;
  pAdvParams->name.xType          = BTGattAdvNameShort;
  pAdvParams->name.ucShortNameLen = IOT_BLE_DEVICE_SHORT_LOCAL_NAME_SIZE;
  pAdvParams->appearance          = IOT_BLE_ADVERTISING_APPEARANCE;
  pAdvParams->minInterval         = IOT_BLE_ADVERTISING_CONN_INTERVAL_MIN;
  pAdvParams->maxInterval         = IOT_BLE_ADVERTISING_CONN_INTERVAL_MAX;
  pAdvParams->serviceDataLen      = 0;
  pAdvParams->pServiceData        = NULL;
  pAdvParams->manufacturerLen     = 0;
  pAdvParams->pManufacturerData   = NULL;
  pAdvParams->pUUID1 = (BTUuid_t *)&_advUUID;
  pAdvParams->pUUID2 = NULL;

  /// use the scan response to fit the full name of the device
  pScanParams->setScanRsp          = true;
  pScanParams->includeTxPower      = false;
  pScanParams->name.xType          = BTGattAdvNameComplete;
  pScanParams->name.ucShortNameLen = 0; // does not matter
  pScanParams->appearance          = IOT_BLE_ADVERTISING_APPEARANCE;
  pScanParams->minInterval         = IOT_BLE_ADVERTISING_CONN_INTERVAL_MIN;
  pScanParams->maxInterval         = IOT_BLE_ADVERTISING_CONN_INTERVAL_MAX;
  pScanParams->serviceDataLen      = 0;
  pScanParams->pServiceData        = NULL;
  pScanParams->manufacturerLen     = 0;
  pScanParams->pManufacturerData   = NULL;
  pScanParams->pUUID1 = NULL;
  pScanParams->pUUID2 = NULL;
}
```

**Additional context**
I have a patch that I will post soon as a PR

### PR DESCRIPTION
**Pull request by matteoscordino**
fix for ESP32 Nimble: prvBTSetAdvData assumes exactly 1 UUID to be advertised

Description
-----------
fixes #1569 :
In iot_ble_hal_gap.c, function prvBTSetAdvData() never uses the xNbServices parameter and assumes there is exactly 1 UUID to be advertised if pxServiceUuid is not NULL.
At the same time, _setAdvData always gives a value to pxServiceUuid and sets xNbServices as 0 if there are no UUIDs to advertise.
This means that trying to advertise 0 UUIDs (e.g. to save advertisement space) does not work. Trying to advertise 2 UUIDs would also not work.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by matteoscordino** [comment]
made the change you suggested, it was a quick one

File: vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c [hunk 1]
```diff
@@ -535,12 +535,13 @@ BTStatus_t prvBTSetAdvData( uint8_t ucAdapterIf,
...
                             size_t xNbServices )
 {
+    const size_t c_max_uuid_per_adv_message = 2;
     struct ble_hs_adv_fields fields;
     const char * name;
     int xESPStatus;
-    ble_uuid16_t uuid16 = { 0 };
-    ble_uuid32_t uuid32 = { 0 };
-    ble_uuid128_t uuid128 = { 0 };
+    ble_uuid16_t uuid16[c_max_uuid_per_adv_message];
```
Comment (ravibhagavandas) [inline vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c]: You don't need the array and `c_max_uuid_per_adv_message` as there can be at max one uuid of each type.

File: vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c [hunk 2]
```diff
@@ -624,32 +624,65 @@ BTStatus_t prvBTSetAdvData( uint8_t ucAdapterIf,
...
     }
 
-    if( pxServiceUuid != NULL )
+    fields.num_uuids16=0;
+    fields.num_uuids32=0;
+    fields.num_uuids128=0;
+    for (size_t i = 0; i < xNbServices; i++)
     {
-        if( pxServiceUuid->ucType == eBTuuidType16 )
+      if( &(pxServiceUuid[i]) != NULL )
```
Comment (ravibhagavandas) [inline vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c]: This check is not needed as  &(pxServiceUuid[i]) can never be NULL.

It makes sense to check for `if( pxServiceUuid != NULL )` before iterating through the array here `for (size_t i = 0; i < xNbServices; i++)`

Comment (matteoscordino) [reply vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c]: `pxServiceUuid[i]` can never be NULL only if we assume the calling code has no bugs.
I think the check is needed as a form of defensive coding, because the caller might have passed a wrong `xNbServices` (i.e. one that is inconsistent with `pxServiceUuid`).
e.g. if the caller passed no services in `pxServiceUuid`, but set `xNbServices` to `1`, removing this check would result in an out-of-bounds memory access.

Comment (ravibhagavandas) [reply vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c]: @matteoscordino 
Array out of bounds cannot be verified using the method you mentioned. Example if array `pxServiceUuid` points to address say `0x1000` and each element size is `K` then  `&pxServiceUuid[N+1]` will be pointing to address `(0x1000 + ( N+1) * K` and this will never be `null(0)`. This would work if `pxServiceUuid is NULL` and user passes `xNbServices > 0` but a better check would be `pxServiceUuid  != NULL` in terms of readability.

Comment (matteoscordino) [reply vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c]: As you prefer, I will make the change.

File: vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c [hunk 3]
```diff
@@ -624,32 +624,65 @@ BTStatus_t prvBTSetAdvData( uint8_t ucAdapterIf,
         fields.svc_data_uuid128_len = usServiceDataLen;
     }
 
+    fields.num_uuids16=0;
+    fields.num_uuids32=0;
+    fields.num_uuids128=0;
     if( pxServiceUuid != NULL )
     {
-        if( pxServiceUuid->ucType == eBTuuidType16 )
+      for (size_t i = 0; i < xNbServices; i++)
```
Comment (gkwicker) [inline vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c]: The code in this loop contains 3 copies of identical operations that differ only in the type they are applied to:

- Set type
- Set value
- Set UUID
- Increment Number of UUIDs of this type
- Set the is_complete flag for this type of UUID

Please refactor this code so that this pattern is only done once in the loop.  An easy way to do this would be with some small utility functions for the UUID16, UUID32, and UUID128 types that this loop calls based on the value of `pxServiceUuid[i].ucType`.

**Comment by matteoscordino** [comment]
Fair point, that code is not optimal.
However, it was there in that form before the PR, it's not code I wrote,
and it is not affected by the code I wrote to fix the issue that I reported.

I think refactoring is out of scope of this PR.


Le mar. 10 déc. 2019 à 23:05, Gary Wicker <notifications@github.com> a
écrit :

File: vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c (hunk 3 above)
Comment (matteoscordino) [reply vendors/espressif/boards/esp32/ports/ble/nimble/iot_ble_hal_gap.c]: Fair point, that code is not optimal.
However, the structure of the code was there in that form before the PR, it's not code I wrote,
and its structure is not affected by the code I wrote to fix the issue that I reported.


I think refactoring that code is out of scope of this PR, whose initial intent was fixing a bug I found in AFR.
